"""add_fallback_to_chat_logs

Revision ID: 8b54abde77eb
Revises: 3aba010170a6
Create Date: 2025-08-05 03:50:53.173202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b54abde77eb'
down_revision: Union[str, None] = '3aba010170a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add fallback column to chat_logs table
    with op.batch_alter_table('chat_logs') as batch_op:
        batch_op.add_column(sa.Column('fallback', sa.Boolean(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_logs') as batch_op:
        batch_op.drop_column('fallback')
    # ### end Alembic commands ###